package view;

/**
 *
 * @author Anonim
 */
public class FDashboard extends javax.swing.JFrame {
    
    

    /**
     * Creates new form FDashboard
     */
    public FDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        bLogout = new javax.swing.JLabel();
        bDataBuku1 = new javax.swing.JLabel();
        bDataBuku = new javax.swing.JLabel();
        bPengembalian = new javax.swing.JLabel();
        bPeminjaman = new javax.swing.JLabel();
        bDashboard = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Selamat Datang di aplikasi E-Library");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, -1, -1));

        bLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bLogoutMouseClicked(evt);
            }
        });
        getContentPane().add(bLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 502, 236, 58));

        bDataBuku1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bDataBuku1MouseClicked(evt);
            }
        });
        getContentPane().add(bDataBuku1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 443, 236, 58));

        bDataBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bDataBukuMouseClicked(evt);
            }
        });
        getContentPane().add(bDataBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 384, 236, 58));

        bPengembalian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bPengembalianMouseClicked(evt);
            }
        });
        getContentPane().add(bPengembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 281, 236, 58));

        bPeminjaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bPeminjamanMouseClicked(evt);
            }
        });
        getContentPane().add(bPeminjaman, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 222, 236, 58));

        bDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bDashboardMouseClicked(evt);
            }
        });
        getContentPane().add(bDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 163, 236, 58));

        user.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        user.setForeground(new java.awt.Color(204, 204, 204));
        getContentPane().add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 76, 70, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/mDashboard.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1181, 590));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bLogoutMouseClicked
        new FLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bLogoutMouseClicked

    private void bDataBuku1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bDataBuku1MouseClicked
        new FDataAnggota().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bDataBuku1MouseClicked

    private void bDataBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bDataBukuMouseClicked
        new FDataBuku().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bDataBukuMouseClicked

    private void bPengembalianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bPengembalianMouseClicked
        new FPengembalian().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bPengembalianMouseClicked

    private void bPeminjamanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bPeminjamanMouseClicked
        new FPeminjaman().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bPeminjamanMouseClicked

    private void bDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bDashboardMouseClicked
        new FDashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bDashboardMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bDashboard;
    private javax.swing.JLabel bDataBuku;
    private javax.swing.JLabel bDataBuku1;
    private javax.swing.JLabel bLogout;
    private javax.swing.JLabel bPeminjaman;
    private javax.swing.JLabel bPengembalian;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
