/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Anonim
 */
public class FPengembalian extends javax.swing.JFrame {

    /**
     * Creates new form FPengembalian
     */
    public FPengembalian() {
        initComponents();
        
        load_Pinjam();
        load_kembali();
        bKembali.setEnabled(false);
    }
    
    //Create data dari Database tbl_anggota
    private void bukuKembali() {
        try {
            Connection kon = koneksi.getConnection();
            Statement st = kon.createStatement();
            //untuk nama peminjman
           String sql = "INSERT INTO tbl_kembali values('" + IDPINJAM.getText()
                    + "','" + tNama.getText()
                    + "','" + tBuku.getText()
                    + "','" + tPinjam.getText()
                    + "','" + tKembali.getText()
                    + "')";
            st.execute(sql);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    private void kembali(){
        try{
            Connection kon = koneksi.getConnection();
            Statement st=kon.createStatement();
            String sql_delete="DELETE from tbl_peminjaman WHERE "
                    +"id_peminjaman='"+IDPINJAM.getText()+"'";
            st.executeUpdate(sql_delete);
            JOptionPane.showMessageDialog(null, "Buku telah Dikembalikan");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    //Load Data Pinjam
    private void load_Pinjam(){
        Object header[] = {"Id Pinjam","Nama Peminjam","Judul Buku","Tangal Pinjam","Tanggal Kembali"};
        DefaultTableModel tableModel = new DefaultTableModel(null, header);
        TABELPINJAM.setModel(tableModel);

        String sql_data="SELECT * FROM tbl_peminjaman";
        try{
            Connection kon = koneksi.getConnection();
            Statement st=kon.createStatement();
            ResultSet rs=st.executeQuery(sql_data);
            while(rs.next()){
                String d1=rs.getString(1);
                String d2=rs.getString(2);
                String d3=rs.getString(3);
                String d4=rs.getString(4);
                String d5=rs.getString(5);

                String d[]={d1,d2,d3,d4,d5};
                tableModel.addRow(d);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
           }
    }
    //Load Data Pinjam
    private void load_kembali(){
        Object header[] = {"Id Pinjam","Nama Peminjam","Judul Buku","Tangal Pinjam","Tanggal Kembali"};
        DefaultTableModel tableModel = new DefaultTableModel(null, header);
        TABELKEMBALI.setModel(tableModel);

        String sql_data="SELECT * FROM tbl_kembali";
        try{
            Connection kon = koneksi.getConnection();
            Statement st=kon.createStatement();
            ResultSet rs=st.executeQuery(sql_data);
            while(rs.next()){
                String d1=rs.getString(1);
                String d2=rs.getString(2);
                String d3=rs.getString(3);
                String d4=rs.getString(4);
                String d5=rs.getString(5);

                String d[]={d1,d2,d3,d4,d5};
                tableModel.addRow(d);
            }
        
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
           }
    }
    
    public void Clear() {
        IDPINJAM.setText(null);
        tNama.setText(null);
        tBuku.setText(null);
        tPinjam.setText(null);
        tKembali.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        IDPINJAM = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        bKembali = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TABELPINJAM = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        tPinjam = new javax.swing.JTextField();
        tNama = new javax.swing.JTextField();
        tBuku = new javax.swing.JTextField();
        tKembali = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TABELKEMBALI = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        bDashboard = new javax.swing.JLabel();
        bPeminjaman = new javax.swing.JLabel();
        bPengembalian = new javax.swing.JLabel();
        bDataBuku = new javax.swing.JLabel();
        bDataBuku1 = new javax.swing.JLabel();
        bLogout = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setText("Tanggal Kembali");

        IDPINJAM.setEditable(false);
        IDPINJAM.setEnabled(false);

        jLabel13.setText("Tanggal Pinjam");

        jLabel14.setText("Nama Buku");

        jLabel15.setText("Id Peminjaman");

        jLabel16.setText("Nama Anggota");

        bKembali.setText("Kembali");
        bKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKembaliActionPerformed(evt);
            }
        });

        TABELPINJAM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TABELPINJAM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TABELPINJAMMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TABELPINJAM);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("Daftar Kembali");

        tPinjam.setEnabled(false);

        tNama.setEnabled(false);

        tBuku.setEnabled(false);

        tKembali.setEnabled(false);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText("Daftar Pinjam");

        TABELKEMBALI.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(TABELKEMBALI);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/refresh.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bKembali))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 785, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel14)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(IDPINJAM, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                            .addComponent(tNama)
                            .addComponent(tBuku))
                        .addGap(99, 99, 99)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tPinjam, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                            .addComponent(tKembali)))
                    .addComponent(jScrollPane2)
                    .addComponent(jLabel18))
                .addGap(50, 50, 50))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(tPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(tKembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(71, 71, 71)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel19)
                                .addComponent(bKembali))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(IDPINJAM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 120, 885, 440));

        bDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bDashboardMouseClicked(evt);
            }
        });
        getContentPane().add(bDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 163, 236, 58));

        bPeminjaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bPeminjamanMouseClicked(evt);
            }
        });
        getContentPane().add(bPeminjaman, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 222, 236, 58));

        bPengembalian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bPengembalianMouseClicked(evt);
            }
        });
        getContentPane().add(bPengembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 281, 236, 58));

        bDataBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bDataBukuMouseClicked(evt);
            }
        });
        getContentPane().add(bDataBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 384, 236, 58));

        bDataBuku1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bDataBuku1MouseClicked(evt);
            }
        });
        getContentPane().add(bDataBuku1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 443, 236, 58));

        bLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bLogoutMouseClicked(evt);
            }
        });
        getContentPane().add(bLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 502, 236, 58));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/mKembali.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1181, 590));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bDashboardMouseClicked
        new FDashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bDashboardMouseClicked

    private void bPeminjamanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bPeminjamanMouseClicked
        new FPeminjaman().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bPeminjamanMouseClicked

    private void bPengembalianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bPengembalianMouseClicked
        new FPengembalian().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bPengembalianMouseClicked

    private void bDataBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bDataBukuMouseClicked
        new FDataBuku().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bDataBukuMouseClicked

    private void bDataBuku1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bDataBuku1MouseClicked
        new FDataAnggota().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bDataBuku1MouseClicked

    private void bLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bLogoutMouseClicked
        new FLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bLogoutMouseClicked

    private void bKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKembaliActionPerformed
        int delete=JOptionPane.showOptionDialog(this, 
                "Apakah Data Benar? Kembalikan?",
                "Kelmbalikan Buku",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, null, null);
        if(delete==JOptionPane.YES_OPTION){
            kembali();
            bukuKembali();
            //Set Enable Input

        }
        load_Pinjam();
        load_kembali();
    }//GEN-LAST:event_bKembaliActionPerformed

    private void TABELPINJAMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TABELPINJAMMouseClicked
        int bar=TABELPINJAM.getSelectedRow();
        String a=TABELPINJAM.getValueAt(bar, 0).toString();
        String b=TABELPINJAM.getValueAt(bar, 1).toString();
        String c=TABELPINJAM.getValueAt(bar, 2).toString();
        String d=TABELPINJAM.getValueAt(bar, 3).toString();
        String e=TABELPINJAM.getValueAt(bar, 4).toString();

        IDPINJAM.setText(a);
        tNama.setText(b);
        tBuku.setText(c);

        //TINGKAT
        tPinjam.setText(d);
        tKembali.setText(e);

        //Set Disable Input
        bKembali.setEnabled(true);
    }//GEN-LAST:event_TABELPINJAMMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        Clear();
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FPengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FPengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FPengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FPengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FPengembalian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDPINJAM;
    private javax.swing.JTable TABELKEMBALI;
    private javax.swing.JTable TABELPINJAM;
    private javax.swing.JLabel bDashboard;
    private javax.swing.JLabel bDataBuku;
    private javax.swing.JLabel bDataBuku1;
    private javax.swing.JButton bKembali;
    private javax.swing.JLabel bLogout;
    private javax.swing.JLabel bPeminjaman;
    private javax.swing.JLabel bPengembalian;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField tBuku;
    private javax.swing.JTextField tKembali;
    private javax.swing.JTextField tNama;
    private javax.swing.JTextField tPinjam;
    // End of variables declaration//GEN-END:variables
}
